### ISSUE TITLE
Add new 1.16 items

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/ItemDbGenerator#4]

**Comment by md678685** [comment]
The [`MainTest#testSignSpawnable` test](https://ci.ender.zone/job/EssentialsX-ItemDbGenerator/io.github.essentialsx$ItemDbGenerator/lastBuild/testReport/io.github.essentialsx.itemdbgenerator/MainTest/testSignSpawnable/) currently checks how many items have sign-friendly aliases.

**Comment by mdcfe** [comment]
Changes to existing items:
- [x] Check whether PIG_ZOMBIE changes in 1.16 (spawner)
- [x] `zombified_piglin_spawn_egg` needs fallback to `zombie_pigman_spawn_egg`

**Comment by mdcfe** [comment]
Missing items:

```
basalt
blackstone
blackstone_slab
blackstone_stairs
blackstone_wall
chiseled_nether_bricks
chiseled_polished_blackstone
cracked_nether_bricks
cracked_polished_blackstone_bricks
gilded_blackstone
polished_basalt
polished_blackstone_brick_slab
polished_blackstone_brick_stairs
polished_blackstone_brick_wall
polished_blackstone_bricks
polished_blackstone_button
polished_blackstone_pressure_plate
polished_blackstone_slab
polished_blackstone_stairs
polished_blackstone_wall
quartz_bricks
soul_campfire
soul_lantern
soul_fire
soul_soil
soul_torch

piglin_banner_pattern
```
